version: '3.9'

services:
  trainers-app:
    image: ${DOCKER_REGISTRY-}app
    container_name: trainer-app
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    depends_on:
      - trainers-db

  trainers-db:
    image: postgres:latest
    container_name: trainer-db
    environment:
      - POSTGRES_DB=trainers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5100:5432

  trainers-db-management:
    image: dpage/pgadmin4:latest
    container_name: Database_management
    depends_on:
      - trainers-db
    volumes:
      - ./.files/dev_servers.json:/pgadmin4/servers.json
      - ./.containers/database_management:/var/lib/pgadmin
    ports:
      - "5101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
